receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        
processors:
  batch:
    timeout: 5s
    send_batch_size: 1000
    send_batch_max_size: 1000
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
    spike_limit_mib: 500

exporters:
  debug:
    verbosity: detailed
    
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [zipkin, debug]