global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dotnet'
    static_configs:
      - targets: ['api-gateway:80', 'order-service:80', 'payment-service:80', 'inventory-service:80']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']